application: amazon-rankings
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: amazon_ranking.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: amazon_ranking.wsgi.application
  secure: always

- url: /static/admin/
  static_dir: sitepackages/prod/django/contrib/admin/static/admin/
  secure: always

- url: /static/rest_framework/
  static_dir: sitepackages/prod/rest_framework/static/rest_framework/
  secure: always

- url: /static/rest_framework_swagger/
  static_dir: sitepackages/prod/rest_framework_swagger/static/rest_framework_swagger/
  secure: always

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: amazon_ranking.wsgi.application
  secure: always
  login: admin

- url: /.*/tasks/.*
  script: amazon_ranking.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: amazon_ranking.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/dev*
    - \.storage.*
    - \.git
    - (.*)\.pyc
